name: workflow_1

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonamos el repositorio
      - uses: actions/checkout@v4
      # Instalamos Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: 'npm'
      # Instalamos dependencias
      - run: npm install
      # Ejecutamos el linter
      - run: npm run lint
      # Ejecutamos las pruebas
      # los pasos pueden tener un nombre, esto ayuda con la depuración
      # el nombre se muestra en Github al revisar la compilación
      - name: run tests
        run: npm test

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
